### ISSUE TITLE
Xcode 7 and Swift 2.0 support

### ISSUE THREAD

**Issue by nootfly** [appsquickly/Typhoon-Swift-Example#14]
I cannot compile the code using Xcode 7.

**Comment by jasperblues** [comment]
Apologies - we'll convert to Swift 2 format ASAP. Looks like there's some issues with the CKUITools pod.

**Comment by jasperblues** [comment]
Sorry for the delay. I've fixed the app so that it at least compiles and runs with Swift 2/iOS9. 

Still needs some attention: 

- The weather API changed, so it doesn’t give days forecast only current conditions. That section is empty. 
- Assets not optimized for iPhone 6
- Should show some storyboards examples
